name: flutter_tools
description: Tools for building Flutter applications
homepage: https://flutter.io
author: Flutter Authors <flutter-dev@googlegroups.com>

environment:
  sdk: '>=1.19.0 <2.0.0'

dependencies:
  # To update these, use "flutter update-packages --force-upgrade".
  archive: 1.0.33
  args: 1.3.0
  cli_util: 0.1.2+1
  coverage: 0.10.0
  crypto: 2.0.2+1
  file: 2.3.6
  http: 0.11.3+16
  intl: 0.15.2
  json_rpc_2: 2.0.7
  json_schema: 1.0.8
  linter: 0.1.43
  meta: 1.1.2
  mustache: 1.0.0
  package_config: 1.0.3
  platform: 2.1.2
  plugin: 0.2.0+2
  process: 2.0.7
  quiver: 0.28.0
  stack_trace: 1.9.1
  stream_channel: 1.6.3
  usage: 3.3.0
  vm_service_client: 0.2.4+1
  web_socket_channel: 1.0.7
  xml: 2.6.0
  yaml: 2.1.13

  # We depend on very specific internal implementation details of the
  # 'test' package, which change between versions, so when upgrading
  # this, make sure the tests are still running correctly.
  test: 0.12.30+3

  # Version from the vended Dart SDK as defined in `dependency_overrides`.
  analyzer: any
  front_end: any

dev_dependencies:
  collection: 1.14.5
  mockito: 2.2.3

  async: 2.0.4 # TRANSITIVE DEPENDENCY
  barback: 0.15.2+14 # TRANSITIVE DEPENDENCY
  boolean_selector: 1.0.2 # TRANSITIVE DEPENDENCY
  charcode: 1.1.1 # TRANSITIVE DEPENDENCY
  convert: 2.0.1 # TRANSITIVE DEPENDENCY
  csslib: 0.14.1 # TRANSITIVE DEPENDENCY
  glob: 1.1.5 # TRANSITIVE DEPENDENCY
  html: 0.13.2+2 # TRANSITIVE DEPENDENCY
  http_multi_server: 2.0.4 # TRANSITIVE DEPENDENCY
  http_parser: 3.1.1 # TRANSITIVE DEPENDENCY
  io: 0.3.2+1 # TRANSITIVE DEPENDENCY
  isolate: 1.1.0 # TRANSITIVE DEPENDENCY
  js: 0.6.1 # TRANSITIVE DEPENDENCY
  logging: 0.11.3+1 # TRANSITIVE DEPENDENCY
  matcher: 0.12.1+4 # TRANSITIVE DEPENDENCY
  mime: 0.9.6 # TRANSITIVE DEPENDENCY
  multi_server_socket: 1.0.1 # TRANSITIVE DEPENDENCY
  node_preamble: 1.4.0 # TRANSITIVE DEPENDENCY
  package_resolver: 1.0.2 # TRANSITIVE DEPENDENCY
  path: 1.5.1 # TRANSITIVE DEPENDENCY
  petitparser: 1.7.0 # TRANSITIVE DEPENDENCY
  pool: 1.3.4 # TRANSITIVE DEPENDENCY
  pub_semver: 1.3.2 # TRANSITIVE DEPENDENCY
  shelf: 0.7.2 # TRANSITIVE DEPENDENCY
  shelf_packages_handler: 1.0.3 # TRANSITIVE DEPENDENCY
  shelf_static: 0.2.7 # TRANSITIVE DEPENDENCY
  shelf_web_socket: 0.2.2 # TRANSITIVE DEPENDENCY
  source_map_stack_trace: 1.1.4 # TRANSITIVE DEPENDENCY
  source_maps: 0.10.4 # TRANSITIVE DEPENDENCY
  source_span: 1.4.0 # TRANSITIVE DEPENDENCY
  string_scanner: 1.0.2 # TRANSITIVE DEPENDENCY
  term_glyph: 1.0.0 # TRANSITIVE DEPENDENCY
  typed_data: 1.1.5 # TRANSITIVE DEPENDENCY
  utf: 0.9.0+4 # TRANSITIVE DEPENDENCY
  watcher: 0.9.7+7 # TRANSITIVE DEPENDENCY

dartdoc:
  # Exclude this package from the hosted API docs.
  nodoc: true

dependency_overrides:
  analyzer:
    path: ../../bin/cache/dart-sdk/lib/analyzer
  front_end:
    path: ../../bin/cache/dart-sdk/lib/front_end
  kernel:
    path: ../../bin/cache/dart-sdk/lib/kernel
