name: flutter_view
description: A new flutter project.

dependencies:
  flutter:
    sdk: flutter

  args: 1.3.0 # TRANSITIVE DEPENDENCY
  async: 2.0.4 # TRANSITIVE DEPENDENCY
  barback: 0.15.2+14 # TRANSITIVE DEPENDENCY
  boolean_selector: 1.0.2 # TRANSITIVE DEPENDENCY
  charcode: 1.1.1 # TRANSITIVE DEPENDENCY
  cli_util: 0.1.2+1 # TRANSITIVE DEPENDENCY
  collection: 1.14.5 # TRANSITIVE DEPENDENCY
  convert: 2.0.1 # TRANSITIVE DEPENDENCY
  crypto: 2.0.2+1 # TRANSITIVE DEPENDENCY
  csslib: 0.14.1 # TRANSITIVE DEPENDENCY
  glob: 1.1.5 # TRANSITIVE DEPENDENCY
  html: 0.13.2+2 # TRANSITIVE DEPENDENCY
  http: 0.11.3+16 # TRANSITIVE DEPENDENCY
  http_multi_server: 2.0.4 # TRANSITIVE DEPENDENCY
  http_parser: 3.1.1 # TRANSITIVE DEPENDENCY
  io: 0.3.2+1 # TRANSITIVE DEPENDENCY
  isolate: 1.1.0 # TRANSITIVE DEPENDENCY
  js: 0.6.1 # TRANSITIVE DEPENDENCY
  logging: 0.11.3+1 # TRANSITIVE DEPENDENCY
  matcher: 0.12.1+4 # TRANSITIVE DEPENDENCY
  meta: 1.1.2 # TRANSITIVE DEPENDENCY
  mime: 0.9.6 # TRANSITIVE DEPENDENCY
  mockito: 2.2.3 # TRANSITIVE DEPENDENCY
  multi_server_socket: 1.0.1 # TRANSITIVE DEPENDENCY
  node_preamble: 1.4.0 # TRANSITIVE DEPENDENCY
  package_config: 1.0.3 # TRANSITIVE DEPENDENCY
  package_resolver: 1.0.2 # TRANSITIVE DEPENDENCY
  path: 1.5.1 # TRANSITIVE DEPENDENCY
  plugin: 0.2.0+2 # TRANSITIVE DEPENDENCY
  pool: 1.3.4 # TRANSITIVE DEPENDENCY
  pub_semver: 1.3.2 # TRANSITIVE DEPENDENCY
  shelf: 0.7.2 # TRANSITIVE DEPENDENCY
  shelf_packages_handler: 1.0.3 # TRANSITIVE DEPENDENCY
  shelf_static: 0.2.7 # TRANSITIVE DEPENDENCY
  shelf_web_socket: 0.2.2 # TRANSITIVE DEPENDENCY
  source_map_stack_trace: 1.1.4 # TRANSITIVE DEPENDENCY
  source_maps: 0.10.4 # TRANSITIVE DEPENDENCY
  source_span: 1.4.0 # TRANSITIVE DEPENDENCY
  stack_trace: 1.9.1 # TRANSITIVE DEPENDENCY
  stream_channel: 1.6.3 # TRANSITIVE DEPENDENCY
  string_scanner: 1.0.2 # TRANSITIVE DEPENDENCY
  term_glyph: 1.0.0 # TRANSITIVE DEPENDENCY
  test: 0.12.30+3 # TRANSITIVE DEPENDENCY
  typed_data: 1.1.5 # TRANSITIVE DEPENDENCY
  utf: 0.9.0+4 # TRANSITIVE DEPENDENCY
  vector_math: 2.0.5 # TRANSITIVE DEPENDENCY
  watcher: 0.9.7+7 # TRANSITIVE DEPENDENCY
  web_socket_channel: 1.0.7 # TRANSITIVE DEPENDENCY
  yaml: 2.1.13 # TRANSITIVE DEPENDENCY

flutter:
  uses-material-design: true
  assets:
    - assets/flutter-mark-square-64.png
